services:
  app:
    build: .
    container_name: vitepress
    # `-- --host` allows localhost of host computer to access docker site.
    command: [ "npm", "run", "docs:dev", "--", "--host"]
    ports:
      - '5173:5173'
    volumes:
      - .:/app